### ISSUE TITLE
Possible typo in the manuscript?

### ISSUE THREAD

**Issue by Feanor007** [marcovarrone/cellcharter#12]
### Report

Congratulations on your exceptional achievement!

Upon perusing your manuscript, I paid particular attention to the Method section, specifically the subsection titled "CellCharter: Neighborhood Enrichment". Within this subsection, the expected value appears to be defined as the summation of kw⋅kw⋅1/2|E|. However, could it possibly be that the definition should be kv⋅kw⋅1/2|E| instead?

**Comment by marcovarrone** [comment]
Hi! 
You are absolutely right, it is indeed a typo and we will update the biorxiv manuscript once we have gathered all the corrections.

Thank you very much for your feedback! 
I really appreciate you taking the time to report it :)
