### ISSUE TITLE
Couldn't import package

### ISSUE THREAD

**Issue by Feanor007** [marcovarrone/cellcharter#13]
### Report

I tried to follow your tutorial on Spatial Clustering on CODEX data. However, I encountered following errors when tried to import packages.
![Screen Shot 2023-06-27 at 05 35 00](https://github.com/CSOgroup/cellcharter/assets/25071118/a2c1f58f-25e2-4515-b435-b362c5ad47b3)

I installed by running `pip install cellcharter[proteomics]`

**Comment by marcovarrone** [comment]
Hi @Feanor007, it looks more like a squidpy problem than a cellcharter one.
Probably the version of squidpy and spatialdata that you have are not fully compatible.

Can you tell me the versions of the squidpy and spatialdata packages currently installed? 
Try to update them and let me know if it works :)

**Comment by Feanor007** [comment]
Thanks for getting back to me earlier.  I'm using version 0.0.12 of spatialdata and version 1.3.0 of squidpy.

Just thought I'd share, I managed to sidestep the error I was dealing with. I did a full reinstall using `pip install cellcharter`, then manually grabbed the trVAE files from /docs/notebooks/. If I skipped the manual download, I ran into an error when I tried running `model = cc.tl.TRVAE.load('./tutorial_models/codex_mouse_spleen_trvae', adata, map_location='cpu')`.

Now, everything's running smoothly and I'm getting the figures from your CODEX tutorial, no problem. One thing that could be cool for the tutorial is if you could include the code for shape characterization, like in Figure 2.h.

Keep up the great work, and thanks again!

**Comment by marcovarrone** [comment]
Thank you very much, I will fix it in the next release!

Yes, the shape analysis will be the next piece of CellCharter that I will add as soon as I finish the differential neighborhood enrichment. 
I will have to do some changes to the original private code because I want to make it compatible with Shapely 2.0 from the beginning.
