### ISSUE TITLE
Installation of cellcharter report import error from `spatialdata._core.data_extent`

### ISSUE THREAD

**Issue by Jieran-S** [marcovarrone/cellcharter#23]
### Report

Hi,

After successfully install the package, I cannot import the package to my workspace. Whenever I tried to import cellcharter, the following error message returns:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[20], line 1
----> 1 import cellcharter as cc

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/cellcharter/__init__.py:3
      1 from importlib.metadata import version
----> 3 from . import datasets, gr, pl, tl
      5 __all__ = ["gr", "pl", "tl", "datasets"]
      7 __version__ = version("cellcharter")

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/cellcharter/pl/__init__.py:4
      2 from ._group import enrichment, proportion
      3 from ._nhood import diff_nhood_enrichment, nhood_enrichment
----> 4 from ._shape import plot_boundaries, plot_shape_metrics

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/cellcharter/pl/_shape.py:15
     13 from anndata import AnnData
     14 from scipy.stats import ttest_ind
---> 15 from spatialdata_plot.pl.utils import _get_colors_for_categorical_obs
     17 from ._utils import adjust_box_widths
     20 def plot_boundaries(
     21     adata: AnnData,
     22     sample: str,
   (...)
     26     show_cells: bool = True,
     27 ) -> None:

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/spatialdata_plot/__init__.py:3
      1 from importlib.metadata import version
----> 3 from . import pl, pp
      5 __all__ = ["pl", "pp"]
      7 __version__ = version("spatialdata-plot")

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/spatialdata_plot/pl/__init__.py:1
----> 1 from .basic import PlotAccessor
      3 __all__ = [
      4     "PlotAccessor",
      5 ]

File ~/conda_envs/cellcharter_env/lib/python3.10/site-packages/spatialdata_plot/pl/basic.py:22
     20 from pandas.api.types import is_categorical_dtype
     21 from spatial_image import SpatialImage
---> 22 from spatialdata._core.data_extent import get_extent
     23 from spatialdata._core.query.relational_query import _locate_value
     24 from spatialdata.transformations.operations import get_transformation

ImportError: cannot import name 'get_extent' from 'spatialdata._core.data_extent' (~/conda_envs/cellcharter_env/lib/python3.10/site-packages/spatialdata/_core/data_extent.py)
```

My environment is as shown below:

### Version information

name: cellcharter_env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - affine=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.9.1=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anndata=0.10.4=pyhd8ed1ab_0
  - aom=3.5.0=h27087fc_0
  - array-api-compat=1.4=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.3=h28f7589_1
  - aws-c-cal=0.6.1=hc309b26_1
  - aws-c-common=0.9.0=hd590300_0
  - aws-c-compression=0.2.17=h4d4d85c_2
  - aws-c-event-stream=0.3.1=h2e3709c_4
  - aws-c-http=0.7.11=h00aa349_4
  - aws-c-io=0.13.32=he9a53bd_1
  - aws-c-mqtt=0.9.3=hb447be9_1
  - aws-c-s3=0.3.14=hf3aad02_1
  - aws-c-sdkutils=0.1.12=h4d4d85c_1
  - aws-checksums=0.1.17=h4d4d85c_1
  - aws-crt-cpp=0.21.0=hb942446_5
  - aws-sdk-cpp=1.10.57=h85b1a90_19
  - blosc=1.21.5=h0f2a231_0
  - bokeh=3.3.3=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h6582d0a_3
  - branca=0.7.0=pyhd8ed1ab_1
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py310hd8f1fbe_9
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.25.0=hd590300_0
  - c-blosc2=2.12.0=hb4ffafa_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - cfitsio=4.2.0=hd9d235c_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.0.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hd41b1e2_0
  - curl=8.4.0=hca28451_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.2=py310h2372a71_1
  - dask=2024.1.0=pyhd8ed1ab_0
  - dask-core=2024.1.0=pyhd8ed1ab_0
  - dask-image=2023.3.0=pyhd8ed1ab_0
  - datashader=0.16.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - distributed=2024.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - expat=2.5.0=hcb278e6_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fiona=1.9.4=py310h111440e_0
  - folium=0.15.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.47.2=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - freexl=1.0.6=h166bdaf_1
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2023.12.2=pyhca7485f_0
  - gdal=3.7.0=py310h65bb550_3
  - geopandas=0.14.2=pyhd8ed1ab_0
  - geopandas-base=0.14.2=pyha770c72_0
  - geos=3.11.2=hcb278e6_0
  - geotiff=1.7.1=h22adcc9_11
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.1=h0b41bf4_3
  - glog=0.6.0=h6f12383_0
  - h5py=3.9.0=nompi_py310hcca72df_101
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.1=nompi_h4f84152_100
  - icu=72.1=hcb278e6_0
  - idna=3.6=pyhd8ed1ab_0
  - imagecodecs=2023.8.12=py310hc929067_0
  - imageio=2.33.1=pyh8c1a49c_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - json-c=0.16=hc379101_0
  - jxrlib=1.1=hd590300_3
  - kealib=1.5.1=h3e6883b_4
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.2=h59595ed_1
  - libarchive=3.6.2=h039dbb9_1
  - libarrow=12.0.1=hb87d912_8_cpu
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcblas=3.9.0=20_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgdal=3.7.0=h4a547c6_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_3
  - libgoogle-cloud=2.12.0=hac9eb74_1
  - libgrpc=1.54.3=hb20ce57_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - libkml=1.3.0=h01aab08_1016
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnetcdf=4.9.2=nompi_h7e745eb_109
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libpq=15.4=hfc447b1_2
  - libprotobuf=3.21.12=hfc55251_2
  - librttopo=1.1.0=h0d5128d_13
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=hca56755_27
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libthrift=0.18.1=h8fd135c_2
  - libtiff=4.5.1=h8b53f26_1
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.11.5=h0d562d8_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=17.0.6=h4dfa4b3_0
  - llvmlite=0.41.1=py310h1b8f574_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310h350c4a5_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - matplotlib-base=3.8.2=py310h62c0568_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2022.2.1=h84fe81f_16997
  - msgpack-python=1.0.7=py310hd41b1e2_0
  - multidict=6.0.4=py310h2372a71_1
  - multipledispatch=0.6.0=py_0
  - multiscale-spatial-image=0.11.2=pyhd8ed1ab_0
  - munch=4.0.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - networkx=3.2.1=pyhd8ed1ab_0
  - ninja=1.11.1=h924138e_0
  - noise=1.2.2=py310h2372a71_1005
  - nspr=4.35=h27087fc_0
  - nss=3.96=h1d7d5a4_0
  - numba=0.58.1=py310h7dc5dd1_0
  - numcodecs=0.12.1=py310hc6cd4ac_0
  - numpy=1.23.4=py310h53a5b5f_1
  - ome-zarr=0.8.3=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.4=hd590300_0
  - orc=1.9.0=h2f23424_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.5.3=py310h9b08913_1
  - param=2.0.2=pyhca7485f_0
  - partd=1.4.1=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=10.0.0=py310h582fbeb_0
  - pims=0.6.1=pyhd8ed1ab_1
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.43.0=h59595ed_0
  - poppler=23.05.0=hd18248d_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.4=h8972f4a_2
  - proj=9.2.1=ha643af7_0
  - psutil=5.9.7=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=12.0.1=py310h0576679_8_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pygeos=0.14=py310h056c13c_1
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproj=3.6.1=py310h177c0e2_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=1.12.1=cpu_py310h02c325b_1
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h1f7b6fc_1
  - pyyaml=6.0.1=py310h2372a71_1
  - rasterio=1.3.8=py310hd227816_0
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rtree=1.1.0=py310hbdcdc62_0
  - s2n=1.3.49=h06160fa_0
  - scikit-learn=1.3.0=py310hf7d194e_0
  - scipy=1.11.4=py310hb13e2d6_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - shapely=2.0.1=py310h056c13c_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - spatial-image=0.3.0=pyhd8ed1ab_0
  - spatialdata=0.0.12=pyhd8ed1ab_0
  - sqlite=3.44.2=h2c6b66d_0
  - tbb=2021.11.0=h00ab1b0_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tifffile=2023.12.9=pyhd8ed1ab_0
  - tiledb=2.13.2=hd532e3d_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchmetrics=0.11.4=pyhd8ed1ab_0
  - tornado=6.3.3=py310h2372a71_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzcode=2023d=h3f72095_0
  - tzdata=2023d=h0c530f3_0
  - ucx=1.14.1=h64cca9d_5
  - unicodedata2=15.1.0=py310h2372a71_0
  - uriparser=0.9.7=hcb278e6_1
  - urllib3=1.26.16=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xarray=2022.12.0=pyhd8ed1ab_0
  - xarray-dataclasses=1.7.0=pyhd8ed1ab_0
  - xarray-datatree=0.0.13=pyhd8ed1ab_0
  - xarray-schema=0.0.3=pyhd8ed1ab_0
  - xerces-c=3.2.4=h8d71039_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2023.10.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zarr=2.16.1=pyhd8ed1ab_0
  - zfp=1.0.1=h59595ed_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - aiobotocore==2.9.1
      - aioitertools==0.11.0
      - botocore==1.33.13
      - cellcharter==0.2.0
      - chex==0.1.7
      - contextlib2==21.6.0
      - dm-tree==0.1.8
      - docrep==0.3.2
      - et-xmlfile==1.1.0
      - etils==1.6.0
      - flax==0.7.2
      - igraph==0.10.8
      - importlib-resources==6.1.1
      - inflect==7.0.0
      - jax==0.4.14
      - jaxlib==0.4.14
      - jmespath==1.0.1
      - leidenalg==0.10.1
      - lightkit==0.5.0
      - lightning-utilities==0.10.0
      - matplotlib-scalebar==0.8.1
      - ml-collections==0.1.1
      - ml-dtypes==0.3.2
      - mudata==0.2.3
      - nest-asyncio==1.5.9
      - numpyro==0.13.2
      - omnipath==1.0.8
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optax==0.1.8
      - orbax-checkpoint==0.5.0
      - patsy==0.5.6
      - protobuf==4.25.2
      - pycave==3.2.1
      - pydantic==1.10.13
      - pynndescent==0.5.11
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pytorch-lightning==1.9.5
      - s3fs==2023.12.2
      - scanpy==1.9.6
      - scikit-image==0.20.0
      - scvi-tools==0.20.3
      - seaborn==0.13.1
      - session-info==1.0.0
      - sknw==0.14
      - spatialdata-plot==0.1.0
      - squidpy==1.3.0
      - statsmodels==0.14.1
      - stdlib-list==0.10.0
      - tensorstore==0.1.52
      - texttable==1.7.0
      - umap-learn==0.5.5
      - validators==0.22.0
      - wrapt==1.16.0
      - xarray-spatial==0.3.7
prefix: /home/jovyan/conda_envs/cellcharter_env

**Comment by Jieran-S** [comment]
Update: After I changed `spatialdata` from 0.0.12 to 0.0.15 the error disappeared, would it be a version conflict of some sort?

**Comment by marcovarrone** [comment]
Same as #24 

Working on it!
