### ISSUE TITLE
cannot import name 'get_extent' from 'spatialdata._core.data_extent

### ISSUE THREAD

**Issue by SBDixit** [marcovarrone/cellcharter#24]
### Report

Hi, thanks a lot for creating this very interesting tool!

I am trying to import cellcharter and I get the following error during the import. It is an issue with spatialdata(0.0.12)itself but would be great to get some help to go about it:
![Capture](https://github.com/CSOgroup/cellcharter/assets/157380477/0d1ad723-50cc-4d10-841a-e190fecc30de)

and I used the below to to install other dependencies 
conda create -n cellcharter-env -c conda-forge python=3.10 mamba
conda activate cellcharter-env
mamba install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
pip install cellcharter
pip install scvi-tools==1.0.3

**Comment by marcovarrone** [comment]
Fixed by #25
