### ISSUE TITLE
Some functions are missing from API docs

### ISSUE THREAD

**Issue by grst** [marcovarrone/cellcharter#34]
### Report

Some functions mentioned in the tutorial, e.g. https://github.com/CSOgroup/cellcharter/blob/396c415f706e46ce5d9b82df062d0b6509aa526e/src/cellcharter/gr/_nhood.py#L136

are missing in the API documentation. Would be great to have the full overview there :)

**Comment by marcovarrone** [comment]
Hi @grst, both the computation and the plotting functions for `nhood_enrichment` are already in the API documentation.
https://cellcharter.readthedocs.io/en/latest/generated/cellcharter.gr.nhood_enrichment.html
or am I missing something?

Is it possible that maybe your browser cached the page? Try to open it in incognito mode.
If this was a cache problem I would check if there is a way to force the refresh of the cache for the users who visit the docs.

EDIT: maybe you were referring to `diff_nhood_enrichment`! I will check all the functions and update the docs. Thanks for the feedback :)

**Comment by grst** [comment]
Hi @marcovarrone, 

I think i was indeed referring to `diff_nhood_enrichment`. Sorry for the confusion!

**Comment by marcovarrone** [comment]
Fixed!
Thank you @grst
