### ISSUE TITLE
cc.pl.plot_boundaries doesn't work

### ISSUE THREAD

**Issue by Feanor007** [marcovarrone/cellcharter#35]
### Report

I am trying to visualize the boundary of neighbourhoods using `cc.pl.plot_boundaries`. However, I received following error messages:

>   sdata = sd.SpatialData(shapes=shapes, table=table)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 sdata = sd.SpatialData(shapes=shapes, table=table)

File /opt/miniconda3/envs/cellcharter-env/lib/python3.10/site-packages/spatialdata/_utils.py:252, in deprecation_alias.<locals>.deprecation_decorator.<locals>.wrapper(*args, **kwargs)
    250 class_name = f.__qualname__
    251 rename_kwargs(f.__name__, kwargs, aliases, class_name)
--> 252 return f(*args, **kwargs)

File /opt/miniconda3/envs/cellcharter-env/lib/python3.10/site-packages/spatialdata/_core/spatialdata.py:155, in SpatialData.__init__(self, images, labels, points, shapes, tables)
    153 if tables is not None:
    154     for k, v in tables.items():
--> 155         self.validate_table_in_spatialdata(v)
    156         self.tables[k] = v
    158 self._query = QueryManager(self)

File /opt/miniconda3/envs/cellcharter-env/lib/python3.10/site-packages/spatialdata/_core/spatialdata.py:180, in SpatialData.validate_table_in_spatialdata(self, table)
    160 def validate_table_in_spatialdata(self, table: AnnData) -> None:
    161     """
    162     Validate the presence of the annotation target of a SpatialData table in the SpatialData object.
    163 
   (...)
    178         The dtypes of the instance key column in the table and the annotation target do not match.
    179     """
--> 180     TableModel().validate(table)
    181     if TableModel.ATTRS_KEY in table.uns:
    182         region, _, instance_key = get_table_keys(table)

File /opt/miniconda3/envs/cellcharter-env/lib/python3.10/site-packages/spatialdata/models/models.py:856, in TableModel.validate(self, data)
    853 if self.ATTRS_KEY not in data.uns:
    854     return data
--> 856 self._validate_table_annotation_metadata(data)
    858 return data

File /opt/miniconda3/envs/cellcharter-env/lib/python3.10/site-packages/spatialdata/models/models.py:828, in TableModel._validate_table_annotation_metadata(self, data)
    824 if (dtype := data.obs[attr[self.INSTANCE_KEY]].dtype) not in [int, np.int16, np.int32, np.int64, "O"] or (
    825     dtype == "O" and (val_dtype := type(data.obs[attr[self.INSTANCE_KEY]].iloc[0])) != str
    826 ):
    827     dtype = dtype if dtype != "O" else val_dtype
--> 828     raise TypeError(
    829         f"Only int, np.int16, np.int32, np.int64 or string allowed as dtype for "
    830         f"instance_key column in obs. Dtype found to be {dtype}"
    831     )
    832 expected_regions = attr[self.REGION_KEY] if isinstance(attr[self.REGION_KEY], list) else [attr[self.REGION_KEY]]
    833 found_regions = data.obs[attr[self.REGION_KEY_KEY]].unique().tolist()

TypeError: Only int, np.int16, np.int32, np.int64 or string allowed as dtype for instance_key column in obs. Dtype found to be category

Here is my code for reproducing this error:
```
cc.pl.plot_boundaries(
    adata,
    sample="BALBc-1",
    library_key='sample',
    component_key="component",
    alpha_boundary=0.5,
    show_cells=True
)
```

Many thanks in advance!

**Comment by EddieLv** [comment]
I found the error comes from function plot_boundaries (line 69), and I can solve it through change it to "adata_obs = ad.AnnData(X=pd.DataFrame(1, index=obs.index, columns=adata.var_names), obs=obs)"

**Comment by marcovarrone** [comment]
Fixed!
