### ISSUE TITLE
error in diff_nhood_enrichment

### ISSUE THREAD

**Issue by Bo-UT** [marcovarrone/cellcharter#39]
### Report

hi, 

Thanks for the great package!
I ran into `TypeError: nhood_enrichment() got an unexpected keyword argument 'condition_groups'`. Thank you!

`cc.gr.diff_nhood_enrichment(
    adata,
    cluster_key='cell_type',
    condition_key='condition',
    library_key='sample',
    # condition_groups = ['condition1', 'condition2'],
    pvalues=True,
    n_jobs=15,
    n_perms=100
)`

<img width="759" alt="Screenshot 2024-05-20 at 11 20 04 AM" src="https://github.com/CSOgroup/cellcharter/assets/55055062/8e0b62b6-973a-4151-90ee-6b0c1ac1f841">

### Version information

-----
anndata             0.10.6
cellcharter         0.2.0
graphcompass        NA
matplotlib          3.8.4
numpy               1.26.4
pandas              2.2.1
scanpy              1.9.8
session_info        1.0.0
squidpy             1.4.1
statsmodels         0.14.0
tqdm                4.66.2
-----
PIL                         10.2.0
affine                      2.4.0
asciitree                   NA
asttokens                   NA
attr                        23.2.0
bottleneck                  1.3.7
brotli                      1.1.0
certifi                     2024.02.02
charset_normalizer          3.3.2
click                       8.1.7
cloudpickle                 3.0.0
colorama                    0.4.6
comm                        0.2.2
cycler                      0.12.1
cython_runtime              NA
dask                        2023.12.1
dask_image                  2023.08.1
datashader                  0.16.0
datatree                    0.0.14
dateutil                    2.9.0
debugpy                     1.8.1
decorator                   5.1.1
docrep                      0.3.2
et_xmlfile                  1.1.0
etils                       1.7.0
exceptiongroup              1.2.0
executing                   2.0.1
fsspec                      2024.3.1
geopandas                   0.14.3
h5py                        3.10.0
idna                        3.6
igraph                      0.11.5
imageio                     2.34.0
importlib_metadata          NA
importlib_resources         NA
ipykernel                   6.29.3
jax                         0.4.19
jaxlib                      0.4.19
jedi                        0.19.1
jinja2                      3.1.3
joblib                      1.3.2
kiwisolver                  1.4.4
lazy_loader                 NA
leidenalg                   0.10.2
lightkit                    NA
lightning_fabric            1.9.0
lightning_utilities         0.11.0
llvmlite                    0.41.1
markupsafe                  2.1.5
matplotlib_inline           0.1.6
matplotlib_scalebar         0.8.1
ml_dtypes                   0.3.2
mpl_toolkits                NA
msgpack                     1.0.8
multipledispatch            0.6.0
multiscale_spatial_image    0.11.2
natsort                     8.4.0
netlsd                      0.0.1
networkx                    3.2.1
numba                       0.58.1
numcodecs                   0.12.1
numexpr                     2.8.7
ome_zarr                    NA
openpyxl                    3.1.2
opt_einsum                  v3.3.0
ot                          0.9.3
packaging                   24.0
param                       2.0.2
parso                       0.8.3
patsy                       0.5.3
pickleshare                 0.7.5
pkg_resources               NA
platformdirs                4.2.0
plotly                      5.22.0
prompt_toolkit              3.0.42
psutil                      5.9.8
pure_eval                   0.2.2
pyarrow                     15.0.2
pycave                      NA
pyct                        0.5.0
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygeos                      0.14
pygments                    2.17.2
pyparsing                   3.0.9
pyproj                      3.6.1
pytorch_lightning           1.9.0
pytz                        2024.1
pywt                        1.6.0
rasterio                    1.3.9
regex                       2.5.145
requests                    2.31.0
rich                        NA
scipy                       1.13.0
seaborn                     0.13.2
setuptools                  68.2.2
shapely                     2.0.3
six                         1.16.0
skimage                     0.20.0
sklearn                     1.4.2
sknw                        0.1
socks                       1.7.1
spatial_image               0.3.0
spatialdata                 0.0.16
spatialdata_plot            0.1.0
stack_data                  0.6.2
tblib                       3.0.0
texttable                   1.7.0
threadpoolctl               3.3.0
tifffile                    2023.12.9
tlz                         0.12.1
toolz                       0.12.1
torch                       1.12.1
torchmetrics                1.3.2
tornado                     6.4
traitlets                   5.14.2
typing_extensions           NA
urllib3                     1.26.18
validators                  0.23.1
vscode                      NA
wcwidth                     0.2.13
wwl                         0.1.2
xarray                      2023.12.0
xarray_dataclasses          1.7.0
xarray_schema               0.0.3
xrspatial                   0.3.7
yaml                        6.0.1
zarr                        2.18.1
zipp                        NA
zmq                         25.1.2
zoneinfo                    NA
-----
IPython             8.22.2
jupyter_client      8.6.1
jupyter_core        5.7.2
-----
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Linux-6.5.0-26-generic-x86_64-with-glibc2.35
-----
Session information updated at 2024-05-20 11:21

**Comment by marcovarrone** [comment]
Hi @Bo-UT! The documentation was more updated than the package on pip :) 
With the latest version (v0.2.1) the parameter should be there!

Fixed by 09849f6346da20b1da5d23fd84d47ac5f9852724
